name: Deploy to VPS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Add SSH Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Prepare Deployment
        env:
          SSH_HOST: ${{ secrets.VPS_HOST }}
          SSH_USERNAME: ${{ secrets.VPS_USERNAME }}
          VPS_PORT: ${{ secrets.VPS_PORT }}
        run: |
          ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -p $VPS_PORT $SSH_USERNAME@$SSH_HOST << 'ENDSSH'
            set -e
            echo "🚀 Starting deployment preparation..."
            
            # Navigate to project directory
            cd /home/sipengaduan
            
            # Fix Git ownership issue
            git config --global --add safe.directory /home/sipengaduan
            
            # Pull latest changes (force pull)
            git fetch --all
            git reset --hard origin/main
            
            echo "✅ Code updated successfully"
          ENDSSH

      - name: Update Environment
        env:
          SSH_HOST: ${{ secrets.VPS_HOST }}
          SSH_USERNAME: ${{ secrets.VPS_USERNAME }}
          VPS_PORT: ${{ secrets.VPS_PORT }}
        run: |
          ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -p $VPS_PORT $SSH_USERNAME@$SSH_HOST << 'ENDSSH'
            set -e
            cd /home/sipengaduan
            
            # Update .env with production values
            echo "${{ secrets.PRODUCTION_ENV }}" > .env
            
            echo "✅ Environment updated successfully"
          ENDSSH

      - name: Build and Deploy Containers
        env:
          SSH_HOST: ${{ secrets.VPS_HOST }}
          SSH_USERNAME: ${{ secrets.VPS_USERNAME }}
          VPS_PORT: ${{ secrets.VPS_PORT }}
        run: |
          ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -p $VPS_PORT $SSH_USERNAME@$SSH_HOST << 'ENDSSH'
            set -e
            cd /home/sipengaduan
            
            echo "🛑 Stopping existing containers..."
            docker compose -f docker-compose.prod.yml down || true
            
            echo "🧹 Cleaning up old images..."
            docker system prune -f
            
            echo "🔨 Building production containers..."
            docker compose -f docker-compose.prod.yml build --no-cache
            
            echo "🚀 Starting production containers..."
            docker compose -f docker-compose.prod.yml up -d
            
            echo "✅ Containers deployed successfully"
          ENDSSH

      - name: Setup Laravel Application
        env:
          SSH_HOST: ${{ secrets.VPS_HOST }}
          SSH_USERNAME: ${{ secrets.VPS_USERNAME }}
          VPS_PORT: ${{ secrets.VPS_PORT }}
        run: |
          ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -p $VPS_PORT $SSH_USERNAME@$SSH_HOST << 'ENDSSH'
            set -e
            cd /home/sipengaduan
            
            echo "⏳ Waiting for application container to be ready..."
            until docker exec sipengaduan-app php -v > /dev/null 2>&1; do
              echo "Waiting for app container..."
              sleep 5
            done
            
            echo "🔧 Running Laravel setup commands..."
            docker exec sipengaduan-app php artisan key:generate --force
            docker exec sipengaduan-app php artisan migrate --force
            docker exec sipengaduan-app php artisan config:cache
            docker exec sipengaduan-app php artisan route:cache
            docker exec sipengaduan-app php artisan view:cache
            docker exec sipengaduan-app php artisan storage:link
            
            echo "✅ Laravel setup completed"
          ENDSSH

      - name: Set Permissions and Finalize
        env:
          SSH_HOST: ${{ secrets.VPS_HOST }}
          SSH_USERNAME: ${{ secrets.VPS_USERNAME }}
          VPS_PORT: ${{ secrets.VPS_PORT }}
        run: |
          ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -p $VPS_PORT $SSH_USERNAME@$SSH_HOST << 'ENDSSH'
            set -e
            cd /home/sipengaduan
            
            echo "🔐 Setting proper permissions..."
            docker exec sipengaduan-app chown -R sipengaduan:www-data /var/www/html/storage
            docker exec sipengaduan-app chown -R sipengaduan:www-data /var/www/html/bootstrap/cache
            docker exec sipengaduan-app chmod -R 775 /var/www/html/storage
            docker exec sipengaduan-app chmod -R 775 /var/www/html/bootstrap/cache
            
            echo "🔄 Restarting services..."
            docker compose -f docker-compose.prod.yml restart
            
            echo "✅ Production deployment completed successfully!"
          ENDSSH
